
default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV['TABLEGAMESITE_ENV'] == "docker" %>
  host: db
  <% else %>
  host: localhost
  <% end %>
  pool: 5
  username: postgres
  password:


#production:
#  <<: *default
#  database: db/production.sqlite3

development:
  <<: *default
  database: tableGameDB

test:
  <<: *default
  database: tableGameTestDB
